name: Update WakaTime Stats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 this line ensures this specific job can push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch WakaTime stats
        id: wakatime
        run: |
          echo "Fetching WakaTime stats..."
          response=$(curl -s -u "${{ secrets.WAKATIME_API_KEY }}:" "https://wakatime.com/api/v1/users/current/all_time_since_today?project=project")

          total_seconds=$(echo $response | jq -r '.data.total_seconds')
          human_readable=$(echo $response | jq -r '.data.text')

          echo "total_seconds=$total_seconds" >> $GITHUB_OUTPUT
          echo "human_readable=$human_readable" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          echo "Updating README.md..."
          sed -i '/<!-- WAKATIME:START -->/,/<!-- WAKATIME:END -->/c\<!-- WAKATIME:START -->\nTotal coding time: **${{ steps.wakatime.outputs.human_readable }}**\n<!-- WAKATIME:END -->' README.md

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "🕒 Update WakaTime stats"
            git push origin HEAD:${{ github.head_ref || github.ref_name }}
          fi
